axios setup added #152
it-for-us/todo pull request #153
Opened 2023-01-15 16:32 UTC by kemaltt

@rdvnbyr 

    const token = sessionStorage.getItem("token"); token i böyle alamiyor anlamadim nedendir, birde app.js de nasil bir islem yapmamiz gerekiyordu biraz arastirdim ama bir cok sey var , app.js de bir islem yapmadim, kisa app.js de nasil bir islem yapmamiz yazabilirsen güzel olur

2023-01-15 20:50 UTC, rdvnbyr commented
Eksik seyler var. Interceptor bir methoddur axios un default ayarlarini degistirmelisin, bunn icin bir "Callback" de yazilabilir.
asagida bir session storage örnegi var. "getItem" veya "setItem" methodlarinin ilk parametresi "key" dir.
`
const testItem = {
  name: 'session-test',
  id: Math.random().toString(36).split('0.')[1],
  date: new Date(),
};
sessionStorage.setItem('test-store', JSON.stringify(testItem));
const store = JSON.parse(sessionStorage.getItem('test-store'));
console.log(store);
`

2023-01-15 20:52 UTC, rdvnbyr commented
> @rdvnbyr
> 
> ```
> const token = sessionStorage.getItem("token"); token i böyle alamiyor anlamadim nedendir, birde app.js de nasil bir islem yapmamiz gerekiyordu biraz arastirdim ama bir cok sey var , app.js de bir islem yapmadim, kisa app.js de nasil bir islem yapmamiz yazabilirsen güzel olur
> ```
> 
> <img alt="Bildschirm­foto 2023-01-15 um 17 34 00" width="793" src="https://user-images.githubusercontent.com/90035121/212553640-a1b4c096-f879-4ff3-a124-44e1a17adf30.png">

https://stackoverflow.com/questions/43051291/attach-authorization-header-for-all-axios-requests
https://axios-http.com/docs/config_defaults
https://stackoverflow.com/questions/51794553/how-do-i-create-configuration-for-axios-for-default-request-headers-in-every-htt

2023-01-16 15:06 UTC, kemaltt commented
@rdvnbyr token tamamdir ,ama app js callback icinde setup edilmis axios u hangi yöntemle yapmam gerektigi noktasinda emin olamadim

2023-01-16 16:21 UTC, rdvnbyr commented
> @rdvnbyr token tamamdir ,ama app js callback icinde setup edilmis axios u hangi yöntemle yapmam gerektigi noktasinda emin olamadim

örnek linklere baktin mi??

2023-01-16 16:50 UTC, kemaltt commented
Evt baktım app js içinde get methodu ile 

axiosExmp.get(' /url') şeklinde  , Callback yada useEffect in içinde

2023-01-17 12:38 UTC, rdvnbyr requested changes
Simdilik kalsin, bunun üzerinden gecelim beraber

2023-01-18 21:51 UTC, rdvnbyr approved these changes

2023-01-18 21:51 UTC, merged